
create table IF NOT EXISTS open_contract(
identifier BIGSERIAL PRIMARY KEY,
barrier NUMERIC(19,4),
barrierCount INTEGER,
bidPrice NUMERIC(19,4),
buyPrice NUMERIC(19,4),
contractId BIGINT,
contractType character varying(255),
currency character varying(255),
currentSpot NUMERIC(19,4),
currentSpotTime BIGINT,
expiryDate BIGINT,
dateSetelment BIGINT,
dateStart BIGINT,
displayName character varying(255),
entryTick NUMERIC(19,4),
entryTickTime BIGINT,
exitTick NUMERIC(19,4),
exitTickTime BIGINT,
isExpired BOOLEAN,
isIntraday BOOLEAN,
isSettleable BOOLEAN,
isValidToSell BOOLEAN,
longCode character varying(255),
payout NUMERIC(19,4),
purchaseTime BIGINT,
sellPrice NUMERIC(19,4),
sellSpot NUMERIC(19,4),
sellSpotTime BIGINT,
sellTime BIGINT,
shortCode character varying(255),
status character varying(30),
validation_error character varying(255)
);
